name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.8.0
      - name: Install dependencies
        working-directory: ./src
        run: npm install
      - name: Test coverage
        working-directory: ./src
        run: npm run test:coverage
      - name: Run ESLint
        working-directory: ./src
        run: npm run eslint || true
      - name: Format eslint for SonarQube
        working-directory: ./utils
        run: node convertPaths.js
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}